version: "0_2_5"


dev_data_location: '../../../data/dev_data/'
spectrograms_location: '../../spectrograms/dev_data_spectrograms/'
spectrogram_dataframes_location: '../../spectrogram_dataframes/dev_data_dataframes/'
fine_tuned_models_location: "../../finetuned_models/"


machine_types: ["gearbox","valve","slider","ToyTrain","fan","pump","ToyCar"]

AST_model:
  nb_layers: 6
  depth_trainable: 3
  input_tdim: 1024
  num_mel_bins: 128
  imagenet_pretrain: True
  audioset_pretrain: True
  model_size: 'base384'
  lr: 0.000000005
  warmup: True
  n_epochs: 50
  batch_size: 16
  shuffle: True
  warmup_steps: 10

save_interval: 10

soft_labels: True

verbose: True

